#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>

int checkP2(int x);
int *dTob(int n,int l);
int bTod(int a[],int l);

int main(){
    int pgs=4; //page size
    int ms=32; //memory size
    int nof=ms/pgs; //number of frames
    int offset_bit; //find out # of bits required for offset
    int m; //find out address spaces required in main memory
    int pg_num_bit; ////find out # of bits required for page number
    int la[]={8,4,3,2,15,18,25}; //logical addresses generated by the CPU
    
    int pmt[]={3,6,8,12,2}; //page table
    
    pg_num_bit = checkP2(nof);
    offset_bit = checkP2(pgs);
    m = checkP2(ms);

    printf("Execution Command in Terminal: ./p1\n");
    printf("Page size: %d\n", pgs);
    printf("Memory size: %d\n", ms);
    printf("Number of frames required: %d\n", nof);
    printf("Page number bits: %d\n", pg_num_bit);
    printf("Offset bits: %d\n", offset_bit);
    printf("Number of address spaces: %d\n", m);

    printf("Page Table_____\n");
    for(int s = 0; s < sizeof(pmt)/sizeof(pmt[0]); s++) {
        printf("%d -> %d\n", s, pmt[s]);
    }

    // Find corresponding physical addresses of generated logical addresses
    for(int s = 0; s < sizeof(la)/sizeof(la[0]); s++) {
        int logic_address = la[s];
        int page = logic_address / pgs;
        int offset = logic_address % pgs;

    
        if (page >= sizeof(pmt)/sizeof(pmt[0])) {
            printf("%d is an invalid page number\n", logic_address);
            continue;
        }

        
        int frame = pmt[page];
        if (frame >= nof) {
            printf("%d is an invalid physical address\n", logic_address);
            continue;
        }

        int physical_address = (frame * pgs) + offset;
        printf("Corresponding physical address of logical address %d: %d\n", logic_address, physical_address);
    }

    return 0;
}

int checkP2(int x){
    int c = 0;
    while (x > 1) {
        x /= 2;
        c++;
    }
    return c;
}

int *dTob(int n,int l){
    static int arr[32];
    return arr;
}

int bTod(int a[],int l){
    return 0;
}